language: c
os: 
- osx
- linux

cache: ccache

before_install:
- brew install --HEAD ccache

script:
- echo $PATH
- ls -al $HOME/.ccache
- ls -al $HOME/ccache
- ccache -s
- make
- ccache -s
- ls -al $HOME/.ccache
- ls -al $HOME/ccache
