language: c
os: osx

cache: 
  directories:
    - $HOME/.ccache

before_install:
- ls -al $HOME/.ccache
- brew install --HEAD ccache
- ls -al $HOME/.ccache


script:
- echo $PATH
- ccache -s
- make
- ccache -s
- ls -al $HOME/.ccache
