language: c
os: osx

cache: 
  directories:
    - $HOME/.ccache

before_install:
- ls -al $HOME/.ccache
- ls -al $HOME/ccache
- ls -al $HOME
- brew install --HEAD ccache

script:
- echo $PATH
- ccache -s
- make
- ccache -s
- ls -al $HOME/.ccache
- ls -al $HOME/ccache
- ls -al $HOME
